### ISSUE TITLE
`aggregatePaginate()` method is not exist

### ISSUE THREAD

**Issue by Yangeok** [WebGangster/mongoose-aggregate-paginate-v2#1]
```js
// models/feed.js
const mongoose = require('mongoose');
const uniqueValidator = require('mongoose-unique-validator');
const mongoosePaginate = require('mongoose-paginate-v2');

const feedsSchema = new mongoose.Schema({
  creator: String,
  title: { type: String, unique: true },
  link: String,
  pubDate: Date
});

feedsSchema.plugin(uniqueValidator);
feedsSchema.plugin(mongoosePaginate);
module.exports = mongoose.model('Feed', feedsSchema);

// query.js
const Feed = require('./models/feed');
let options = {
  page: 1,
  limit: 10
};

const aggregate = Feed.aggregate();
Feed.aggregatePaginate(aggregate, options)
  .then(results => {
    console.log(results)
}).catch(err => {
    console.log(err);
});
```

I followed the tutorial, but it prints a function in the console that does not have an aggregatePaginate () method. What is wrong and what should I do?

**Comment by aravindnc** [comment]
@Yangeok  You are including the wrong package. 
It should be,
const mongoosePaginate =  require('mongoose-aggregate-paginate-v2');

**Comment by Yangeok** [comment]
Then you need both package mongoose-paginate-v2 and mongoose-aggregate-paginate-v2. So the npm page is not up to date?

**Comment by aravindnc** [comment]
mongoose-aggregate-paginate-v2 is only for aggregate.
mongoose-paginate-v2 does not support aggregate.

So you may need both in your project.

**Comment by Yangeok** [comment]
I mistook the document. I had to look at usage in mongoose-paginate-v2 and saw usage in mongoose-aggregate-paginate-v2.

Thank you for your help.

**Comment by aravindnc** [comment]
@Yangeok Glad to hear that. 
So I'm closing the issue. Please reopen if needed.
Happy Coding!
